spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: myuser
    password: mypassword
  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    password: mypassword
    baseline-on-migrate: true
    user: myuser

